parameters:
#    profesor.example.class: evaluaUcab\ProfesorBundle\Example

services:
#    profesor.example:
#        class: %profesor.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
