parameters:
#    estudiante.example.class: evaluaUcab\EstudianteBundle\Example

services:
#    estudiante.example:
#        class: %estudiante.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
